INSERT INTO PUBLIC.SCORE(ID, STUDENT_ID, TEACHER_ID, EDU_PROGRAM_DISCIPLINE_ID, SCORE, ATTEMPT, date)
VALUES (
	(SELECT (MAX(ID) + 1) FROM SCORE),
	2,
	3,
	3,
	5,
	(SELECT (ATTEMPT + 1) FROM SCORE WHERE SCORE.STUDENT_ID = 2 AND SCORE.EDU_PROGRAM_DISCIPLINE_ID = 3),
	'2023-01-01'
);