-- Удалить назначение стипендии у студентов, у которых была получена хоть одна тройка за сессию

DELETE
FROM SCHOLARSHIP_ASSIGNMENT
WHERE SCHOLARSHIP_ASSIGNMENT.PERSON_ID in
		(SELECT SCORE.STUDENT_ID
			FROM PERSON
			JOIN STUDENT ON PERSON.ID = STUDENT.ID
			JOIN SCORE ON SCORE.STUDENT_ID = STUDENT.ID
			WHERE SCORE.SCORE < 4)