SELECT STUDENT_GROUP.CODE,
	AVG(SCORE) AS AVG_SCORE
FROM SCORE
JOIN STUDENT_GROUP ON STUDENT_GROUP.ID =
	(SELECT STUDENT_GROUP_ID
		FROM STUDENT
		WHERE STUDENT.ID = SCORE.STUDENT_ID)
WHERE STUDENT_GROUP.CURRICULUM_ID = 4
GROUP BY STUDENT_GROUP.CODE
ORDER BY AVG(SCORE.SCORE) DESC