SELECT PERSON.SURNAME,
	STUDENT_GROUP.CODE,
	CASE
		WHEN MIN(SCORE.SCORE) > 3 THEN 1
		ELSE 0
	END AS SHOULD_HAVE_SCHOLARSHIP
FROM SCORE
JOIN STUDENT_GROUP ON STUDENT_GROUP.ID =
	(SELECT STUDENT_GROUP_ID
		FROM STUDENT
		WHERE STUDENT.ID = SCORE.STUDENT_ID)
JOIN PERSON ON PERSON.ID =
	(SELECT PERSON_ID
		FROM STUDENT
		WHERE ID = SCORE.STUDENT_ID)
GROUP BY PERSON.SURNAME,
	STUDENT_GROUP.CODE
ORDER BY PERSON.SURNAME,
	STUDENT_GROUP.CODE