SELECT PERSON.SURNAME,
	DISCIPLINE.ID AS DISCIPLINE_ID
FROM SCORE
JOIN PERSON ON PERSON.ID =
	(SELECT PERSON_ID
		FROM STUDENT
		WHERE ID = SCORE.STUDENT_ID)
JOIN DISCIPLINE ON DISCIPLINE.ID =
	(SELECT DISCIPLINE_ID
		FROM EDU_PROGRAM_DISCIPLINE
		WHERE ID = SCORE.EDU_PROGRAM_DISCIPLINE_ID)
JOIN
	(SELECT EDU_PROGRAM_DISCIPLINE_ID,
			AVG(SCORE.SCORE) AS AVG_SCORE
		FROM SCORE
		GROUP BY EDU_PROGRAM_DISCIPLINE_ID) AVG_SCORE ON SCORE.EDU_PROGRAM_DISCIPLINE_ID = AVG_SCORE.EDU_PROGRAM_DISCIPLINE_ID
WHERE SCORE.SCORE > AVG_SCORE.AVG_SCORE