SELECT SCORE.STUDENT_ID
FROM SCORE
JOIN
	(SELECT STUDENT_ID,
			EDU_PROGRAM_DISCIPLINE_ID,
			MAX(ATTEMPT) AS LAST_ATTEMPT
		FROM SCORE
		GROUP BY (STUDENT_ID, EDU_PROGRAM_DISCIPLINE_ID)) ATTEMPTS ON SCORE.ATTEMPT = LAST_ATTEMPT
AND SCORE.STUDENT_ID = ATTEMPTS.STUDENT_ID
AND SCORE.EDU_PROGRAM_DISCIPLINE_ID = ATTEMPTS.EDU_PROGRAM_DISCIPLINE_ID
GROUP BY SCORE.STUDENT_ID
HAVING MIN(SCORE.SCORE) > 2