SELECT STUDENT_ID,
	STUDENT_GROUP.ID AS STUDENT_GROUP_ID,
	AVG_STUDENT_SCORE
FROM
	(SELECT STUDENT_ID,
			AVG(SCORE) AS AVG_STUDENT_SCORE
		FROM SCORE
		GROUP BY STUDENT_ID) AVG_STUDENT_SCORE
JOIN STUDENT AVG_STUDENT ON AVG_STUDENT.ID = AVG_STUDENT_SCORE.STUDENT_ID
JOIN STUDENT_GROUP ON STUDENT_GROUP.ID = AVG_STUDENT.STUDENT_GROUP_ID
JOIN
	(SELECT STUDENT_GROUP.ID,
			MAX(AVG_STUDENT_SCORE) AS MAX_GROUP_AVG_SCORE
		FROM SCORE
		JOIN STUDENT MAX_STUDENT ON SCORE.STUDENT_ID = MAX_STUDENT.ID
		JOIN STUDENT_GROUP ON STUDENT_GROUP.ID = MAX_STUDENT.STUDENT_GROUP_ID
		JOIN
			(SELECT STUDENT_ID,
					AVG(SCORE) AS AVG_STUDENT_SCORE
				FROM SCORE
				GROUP BY STUDENT_ID) INNER_AVG_SCORE ON SCORE.STUDENT_ID = INNER_AVG_SCORE.STUDENT_ID
		GROUP BY STUDENT_GROUP.ID) AS MAX_GROUP_AVG ON STUDENT_GROUP.ID = MAX_GROUP_AVG.ID
WHERE AVG_STUDENT_SCORE = MAX_GROUP_AVG_SCORE