SELECT PERSON.SURNAME,
	PERSON.NAME,
	PERSON.MIDDLE_NAME,
	TEACHER.SURNAME
FROM SCORE
JOIN PERSON ON PERSON.ID =
	(SELECT PERSON_ID
		FROM STUDENT
		WHERE ID = SCORE.STUDENT_ID)
JOIN TEACHER ON TEACHER.ID = SCORE.TEACHER_ID
WHERE SCORE.ATTEMPT = 1
	AND SCORE.SCORE = 2