SELECT date, SURNAME
FROM ASSESSMENT
JOIN TEACHER ON ASSESSMENT.TEACHER_ID = TEACHER.ID
WHERE EDU_PROGRAM_DISCIPLINE_ID =
		(SELECT ID
			FROM EDU_PROGRAM_DISCIPLINE
			WHERE ID =
					(SELECT ID
						FROM EDUCATIONAL_PROGRAM
						WHERE ID =
								(SELECT EDUCATIONAL_PROGRAM_ID
									FROM CURRICULUM
									WHERE CURRICULUM.ID =
											(SELECT CURRICULUM_ID
												FROM STUDENT_GROUP
												WHERE STUDENT_GROUP.CODE = 'K32401'))))