# Generated by Django 4.2.1 on 2023-05-28 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('CAT', 'Cat'), ('Dog', 'Dog'), ('OTHER', 'Unknown creature')], max_length=40)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('species_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.species')),
            ],
        ),
    ]
