# Generated by Django 4.2.1 on 2023-05-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
