CREATE TABLE meetings (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  invite_text VARCHAR(280) NOT NULL,
  start_at TIMESTAMP NOT NULL,
  peer_id INTEGER NOT NULL
)